### ISSUE TITLE
Super large number of epoch

### ISSUE THREAD

**Issue by Harry-py** [huggingface/community-events#103]
Thanks for providing the code for fine-tuning!

Issue:
I am running into an issue when i call `trainer.train()`, I get super large number of epoch as shown below.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/66230476/215696803-150ac311-a8e4-49f8-a88a-1bdd3475f8dc.png">

I have tried specifying num_train_epochs, which didn't work. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/66230476/215698020-8b206a2d-4c04-45b0-994f-e32d4e19741f.png">

Training context: 
I am finetuning in colab, referencing [this script](https://colab.research.google.com/github/huggingface/community-events/blob/main/whisper-fine-tuning-event/fine_tune_whisper_streaming_colab.ipynb). I am fine-tuning the tiny model for Chinese(zh-TW), and only modified the code where necessary. My script is here: [colab link](https://colab.research.google.com/drive/1jVw6XJHJako0-YlFKWBz_6rIm5KPdv8q?hl=en#scrollTo=0ae3e9af-97b7-4aa0-ae85-20b23b5bcb3a)

**Comment by Vaibhavs10** [comment]
Hi @Harry-py - Sorry for the delayed response. Just to answer your question, since you are using the streaming mode, the model doesn't really know the exact count of data points available, hence it gives an obsenely high number of epochs.

Feel free to open this issue again in case you have any furthere questions.
